# Generated by Django 4.2.3 on 2023-12-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloneApp', '0003_hero_subsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_netcore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(default='', upload_to='cloneApp/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero_subsection',
        ),
    ]
