# Generated by Django 4.2.3 on 2023-12-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloneApp', '0004_why_netcore_delete_hero_subsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Why_netcore',
        ),
    ]
