# Generated by Django 4.2.3 on 2023-12-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloneApp', '0008_about_delete_hero_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
