# Generated by Django 4.2.3 on 2023-12-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloneApp', '0014_landing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Landing',
        ),
        migrations.DeleteModel(
            name='Our_involvement',
        ),
    ]
